version: "3.8"
services:
  jupyterlab:
    image:
        registry.dvclab.com/${image_name}
    container_name: ${container_id}
    privileged: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - container_id=${container_id}
      - frp_service_url=${frp_service_url}
      - project_git_url=${project_git_url}.git
      - project_branch=${project_branch}
      - project_name=${project_name}
      ${datasets}
      - pypi_repo=https://bandersnatch.dvclab.com/simple
      - uid=${uid}
      - keycloak_server_addr=${keycloak_server_addr}
      - keycloak_realm=${keycloak_realm}
      - client_id=${client_id}
      - resource_server=${resource_server}
      - scope=openid+email
      - service_addr=${service_addr}
      - kafka_server=${kafka_server}
      - kafka_topic=${kafka_topic}
      - CPU=${cpus}
      - MEM=${mem}
    entrypoint: /opt/init_container.sh
    ${runtime}
    deploy:
      resources:
        limits:
          cpus: "${cpus}"
          memory: "${mem}G"